version: '3'
services:

  ## Config Servers
  config01:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
  config02:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts
  config03:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver
    volumes:
      - ./scripts:/scripts

  ## Shards
  shard01a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./scripts:/scripts
  shard01b:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./scripts:/scripts
  shard01c:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01
    volumes:
      - ./scripts:/scripts
      
  shard02a:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02
    volumes:
      - ./scripts:/scripts
  shard02b:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02
    volumes:
      - ./scripts:/scripts
  shard02c:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02
    volumes:
      - ./scripts:/scripts

  shard03a:
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03
    volumes:
      - ./scripts:/scripts
  shard03b:
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03
    volumes:
      - ./scripts:/scripts
  shard03c:
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03
    volumes:
      - ./scripts:/scripts

  shard04a:
    image: mongo
    command: mongod --port 27021 --shardsvr --replSet shard04
    volumes:
      - ./scripts:/scripts
  shard04b:
    image: mongo
    command: mongod --port 27021 --shardsvr --replSet shard04
    volumes:
      - ./scripts:/scripts
  shard04c:
    image: mongo
    command: mongod --port 27021 --shardsvr --replSet shard04
    volumes:
      - ./scripts:/scripts

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017,config03:27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
      - ./data:/data
